# Generated by Django 4.0.3 on 2022-04-11 07:04

import django.db.models.deletion
import sorl.thumbnail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제일')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('placement_name', models.CharField(blank=True, max_length=100)),
                ('placement_owner', models.CharField(blank=True, max_length=20)),
                ('placement_address', models.CharField(blank=True, max_length=100)),
                ('placement_type', models.PositiveSmallIntegerField(choices=[(0, 'Service'), (1, 'Direct'), (2, 'Exchange')], default=0)),
                ('operation_start', models.TimeField()),
                ('operation_end', models.TimeField()),
                ('operation_state', models.PositiveSmallIntegerField(choices=[(0, 'Operating'), (1, 'Constructing'), (2, 'Soon')], default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlacementImage',
            fields=[
                ('is_created', models.DateTimeField(auto_now_add=True)),
                ('is_updated', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제일')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', sorl.thumbnail.fields.ImageField(null=True, upload_to='place/%Y/%M')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement.placement')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
