# Generated by Django 4.0.2 on 2022-02-21 11:43

from django.db import migrations, models
import django.db.models.deletion
import placement.constant
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('placement_name', models.CharField(blank=True, max_length=100)),
                ('placement_owner', models.CharField(blank=True, max_length=20)),
                ('placement_address', models.CharField(blank=True, max_length=100)),
                ('placement_type', models.PositiveSmallIntegerField(default=placement.constant.PlacementType['SERVICE'])),
                ('operation_start', models.TimeField()),
                ('operation_end', models.TimeField()),
                ('operation_state', models.PositiveSmallIntegerField(default=placement.constant.OperationState['OPERATING'])),
            ],
        ),
        migrations.CreateModel(
            name='PlacementImage',
            fields=[
                ('is_created', models.DateTimeField(auto_now_add=True)),
                ('is_updated', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', sorl.thumbnail.fields.ImageField(upload_to='place/%Y/%M')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement.placement')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
