# Generated by Django 4.0.1 on 2022-01-23 04:31

from django.db import migrations, models
import placement.constant


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='placement_type',
            field=models.PositiveSmallIntegerField(default=placement.constant.PlacementType['SERVICE']),
        ),
    ]
