# Generated by Django 4.0.4 on 2022-04-20 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placementimage',
            name='deleted_at',
        ),
    ]
