# Generated by Django 4.0.1 on 2022-01-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='operation_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='placement',
            name='operation_start',
            field=models.DateTimeField(),
        ),
    ]
