# Generated by Django 4.0.2 on 2022-03-11 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='operation_state',
            field=models.PositiveSmallIntegerField(choices=[('service', 'Service'), ('direct', 'Direct'), ('exchange', 'Exchange')], default=0),
        ),
        migrations.AlterField(
            model_name='placement',
            name='placement_type',
            field=models.PositiveSmallIntegerField(choices=[('service', 'Service'), ('direct', 'Direct'), ('exchange', 'Exchange')], default='service'),
        ),
    ]
