# Generated by Django 4.0.1 on 2022-01-23 04:44

from django.db import migrations, models
import placement.constant


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0002_alter_placement_placement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='operation_state',
            field=models.PositiveSmallIntegerField(default=placement.constant.OperationState['OPERATING']),
        ),
    ]
