# Generated by Django 4.0.2 on 2022-03-11 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0002_alter_placement_operation_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='placement_type',
            field=models.CharField(choices=[('service', 'Service'), ('direct', 'Direct'), ('exchange', 'Exchange')], default='service', max_length=10),
        ),
    ]
