# Generated by Django 4.0.4 on 2022-04-22 11:35

from django.db import migrations, models
import placement.constant


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0002_remove_placementimage_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='placement_type',
            field=models.PositiveSmallIntegerField(default=placement.constant.PlacementType['SERVICE']),
        ),
    ]
