# Generated by Django 4.0.2 on 2022-03-11 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0003_alter_placement_placement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='operation_state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Operating'), (1, 'Constructing'), (2, 'Soon')], default=0),
        ),
        migrations.AlterField(
            model_name='placement',
            name='placement_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Service'), (1, 'Direct'), (2, 'Exchange')], default=0),
        ),
    ]
