# Generated by Django 4.0.2 on 2022-03-13 14:50

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0004_alter_placement_operation_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementimage',
            name='file',
            field=sorl.thumbnail.fields.ImageField(null=True, upload_to='place/%Y/%M'),
        ),
    ]
