# Generated by Django 4.0.1 on 2022-01-14 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDisplayLine',
            fields=[
                ('display_line_no', models.AutoField(primary_key=True, serialize=False)),
                ('display_line_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_no', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_name', models.CharField(max_length=200)),
                ('zero_to_fifty', models.IntegerField(default=0)),
                ('max_speed', models.IntegerField(default=0)),
                ('max_output', models.IntegerField(default=0)),
                ('subsidy', models.IntegerField(default=0)),
                ('extra_subsidy', models.IntegerField(default=0)),
                ('is_display', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleSubsidy',
            fields=[
                ('subsidy_no', models.AutoField(primary_key=True, serialize=False)),
                ('subsidy_name', models.CharField(max_length=100)),
                ('subsidy_amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_no', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('product_price', models.IntegerField(default=0)),
                ('is_display', models.BooleanField(default=False)),
                ('is_refundable', models.BooleanField(default=False)),
                ('display_line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productdisplayline')),
            ],
        ),
    ]
