# Generated by Django 4.0.4 on 2022-04-19 04:59

import colorfield.fields
import django.db.models.deletion
import sorl.thumbnail.fields
from django.db import migrations, models

import product.constant


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('is_created', models.DateTimeField(auto_now_add=True)),
                ('is_updated', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제일')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('product_price', models.IntegerField(default=0)),
                ('product_label', models.PositiveSmallIntegerField(default=product.constant.ProductLabel['NEW'])),
                ('is_display', models.BooleanField(default=False)),
                ('is_refundable', models.BooleanField(default=False)),
                ('product_description', models.TextField(blank=True, default='')),
                ('shipping_instructions', models.TextField(blank=True, default='')),
                ('refund_instructions', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductDisplayLine',
            fields=[
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제일')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('display_line_name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제일')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_name', models.CharField(max_length=200)),
                ('zero_to_fifty', models.IntegerField(default=0)),
                ('max_speed', models.IntegerField(default=0)),
                ('max_output', models.IntegerField(default=0)),
                ('able_subsidy', models.BooleanField(default=False)),
                ('able_extra_subsidy', models.BooleanField(default=False)),
                ('is_display', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleColor',
            fields=[
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제일')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('color_name', models.CharField(blank=True, max_length=20)),
                ('stock_count', models.IntegerField(default=0)),
                ('sale_count', models.IntegerField(default=0)),
                ('hex_code', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None)),
                ('on_sale', models.BooleanField(default=False)),
                ('price', models.IntegerField(default=0)),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('is_created', models.DateTimeField(auto_now_add=True)),
                ('is_updated', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제일')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('origin_image', sorl.thumbnail.fields.ImageField(null=True, upload_to='vehicle/%Y/%M')),
                ('vehicle_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.vehiclecolor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductOptions',
            fields=[
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제일')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('option_name', models.CharField(blank=True, max_length=200)),
                ('option_description', models.TextField(blank=True)),
                ('is_apply', models.BooleanField(default=False)),
                ('product_options_label', models.PositiveSmallIntegerField(default=product.constant.ProductOptionsLabel['NORMAL'], help_text='0 : 일반형, 1 : 입력형, 2: 해당 없음')),
                ('sale_count', models.IntegerField(default=0)),
                ('stock_count', models.IntegerField(default=0)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('is_created', models.DateTimeField(auto_now_add=True)),
                ('is_updated', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제일')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('origin_image', sorl.thumbnail.fields.ImageField(null=True, upload_to='product/%Y/%M')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_display_line',
            field=models.ManyToManyField(to='product.productdisplayline'),
        ),
    ]
