# Generated by Django 4.0.1 on 2022-01-24 05:44

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_display_line',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_options',
        ),
        migrations.RemoveField(
            model_name='productoptions',
            name='product_image',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_color',
        ),
        migrations.AddField(
            model_name='productimage',
            name='product_options_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productoptions'),
        ),
        migrations.AddField(
            model_name='vehiclecolor',
            name='vehicle_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.vehicle'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='origin_image',
            field=sorl.thumbnail.fields.ImageField(upload_to='thumb/%Y/%M/%D/%HH/%MM/%SS5593'),
        ),
    ]
