# Generated by Django 4.0.1 on 2022-01-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_display_line_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VehicleSubsidy',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='extra_subsidy',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='subsidy',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='able_extra_subsidy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='able_subsidy',
            field=models.BooleanField(default=False),
        ),
    ]
