# Generated by Django 4.0.3 on 2022-03-28 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicleimage',
            old_name='vehicle',
            new_name='vehicle_color',
        ),
    ]
