# Generated by Django 4.0.3 on 2022-03-30 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_vehicle_vehicleimage_vehicle_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleimage',
            name='vehicle_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.vehiclecolor'),
        ),
    ]
