# Generated by Django 4.0.1 on 2022-01-24 06:21

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_product_display_line_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='origin_image',
            field=sorl.thumbnail.fields.ImageField(upload_to='thumb/%Y/%M/%D/%HH/%MM/%SS231'),
        ),
    ]
