# Generated by Django 4.0.2 on 2022-02-17 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_product_productoptions_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productoptions',
            old_name='product_id',
            new_name='product',
        ),
    ]
