# Generated by Django 4.0.1 on 2022-01-26 07:39

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productimage_origin_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='origin_image',
            field=sorl.thumbnail.fields.ImageField(upload_to='thumb/%Y/%M/%D/%HH/%MM/%SS59124'),
        ),
        migrations.AlterField(
            model_name='vehiclecolor',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_color', to='product.vehicle'),
        ),
    ]
