# Generated by Django 4.0.1 on 2022-01-24 06:31

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productimage_origin_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_display_line_id',
            field=models.ManyToManyField(default=None, null=True, to='product.ProductDisplayLine'),
        ),
        migrations.AddField(
            model_name='productdisplayline',
            name='product_id',
            field=models.ManyToManyField(null=True, to='product.Product'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='origin_image',
            field=sorl.thumbnail.fields.ImageField(upload_to='thumb/%Y/%M/%D/%HH/%MM/%SS61856'),
        ),
    ]
