# Generated by Django 4.0.1 on 2022-01-20 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productdisplayline_product_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VehicleColorModel',
            new_name='VehicleColor',
        ),
        migrations.RemoveField(
            model_name='productdisplayline',
            name='product_id',
        ),
        migrations.AddField(
            model_name='product',
            name='product_display_line_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productdisplayline'),
        ),
    ]
