# Generated by Django 4.0.1 on 2022-01-26 15:28

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productoptions_option_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclecolor',
            name='color_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vehiclecolor',
            name='hex_code',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='vehiclecolor',
            name='on_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiclecolor',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehiclecolor',
            name='stock_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='origin_image',
            field=sorl.thumbnail.fields.ImageField(upload_to='thumb/%Y/%M/%D/%HH/%MM/%SS34317'),
        ),
        migrations.AlterField(
            model_name='vehiclecolor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicleimage',
            name='origin_image',
            field=sorl.thumbnail.fields.ImageField(upload_to='thumb/%Y/%M/%D/%HH/%MM/%SS67230'),
        ),
    ]
