# Generated by Django 4.0.1 on 2022-01-24 06:34

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_product_display_line_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdisplayline',
            name='product_id',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_display_line_id',
            field=models.ManyToManyField(to='product.ProductDisplayLine'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='origin_image',
            field=sorl.thumbnail.fields.ImageField(upload_to='thumb/%Y/%M/%D/%HH/%MM/%SS44463'),
        ),
    ]
