# Generated by Django 4.0.1 on 2022-01-26 15:47

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_vehiclecolor_color_name_vehiclecolor_hex_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='origin_image',
            field=sorl.thumbnail.fields.ImageField(upload_to='thumb/%Y/%M/%D/%HH/%MM/%SS23631'),
        ),
        migrations.AlterField(
            model_name='vehicleimage',
            name='origin_image',
            field=sorl.thumbnail.fields.ImageField(upload_to='thumb/%Y/%M/%D/%HH/%MM/%SS7966'),
        ),
    ]
