# Generated by Django 4.0.1 on 2022-02-03 01:53

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_productimage_origin_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='origin_image',
            field=sorl.thumbnail.fields.ImageField(upload_to='thumb/%Y/%M/%D/%HH/%MM/%SS87485'),
        ),
        migrations.AlterField(
            model_name='vehicleimage',
            name='origin_image',
            field=sorl.thumbnail.fields.ImageField(upload_to='thumb/%Y/%M/%D/%HH/%MM/%SS89402'),
        ),
    ]
