# Generated by Django 4.0.1 on 2022-02-03 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_remove_productimage_origin_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='thumb-product121278856358952',
            new_name='origin_image',
        ),
        migrations.RenameField(
            model_name='vehicleimage',
            old_name='thumb-vehicle1778947343881',
            new_name='origin_image',
        ),
    ]
