# Generated by Django 4.0.1 on 2022-02-06 08:05

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_rename_thumb-product121278856358952_productimage_origin_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='origin_image',
            field=sorl.thumbnail.fields.ImageField(null=True, upload_to='product/%Y/%M'),
        ),
        migrations.AlterField(
            model_name='vehicleimage',
            name='origin_image',
            field=sorl.thumbnail.fields.ImageField(null=True, upload_to='vehicle/%Y/%M'),
        ),
    ]
