# Generated by Django 4.0.1 on 2022-01-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=200)),
                ('is_created', models.DateTimeField(default=(2022, 1, 13, 5, 50, 6, 3, 13, 0))),
            ],
        ),
    ]
