# Generated by Django 4.0.1 on 2022-01-23 04:52

from django.db import migrations, models
import post.constant


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.PositiveSmallIntegerField(default=post.constant.PostType['NOTICE']),
        ),
    ]
