# Generated by Django 4.0.1 on 2022-01-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Faq'), (1, 'Notice')], default=1),
        ),
    ]
