# Generated by Django 4.0.1 on 2022-01-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_created',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
