# Generated by Django 4.0.1 on 2022-01-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_is_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[('0', 'Faq'), ('1', 'Notice')], default='1'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
