# Generated by Django 4.0.1 on 2022-01-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_rename_type_post_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.IntegerField(choices=[(0, 'Faq'), (1, 'Notice')], default=1),
        ),
    ]
