# Generated by Django 4.0.1 on 2022-01-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
