# Generated by Django 4.0.1 on 2022-01-20 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_post_is_created_alter_post_is_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
