# Generated by Django 4.0.1 on 2022-02-05 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='is_created',
        ),
        migrations.RemoveField(
            model_name='member',
            name='is_updated',
        ),
    ]
