# Generated by Django 4.0.2 on 2022-02-12 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_is_vehicle_alter_order_owner'),
        ('product', '0001_initial'),
        ('history', '0003_afterservice_owner'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='MemberOwnedVehicles',
            fields=[
                ('is_created', models.DateTimeField(auto_now_add=True)),
                ('is_updated', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('license_code', models.CharField(max_length=20)),
                ('battery_left', models.FloatField(default=0.0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
                ('recent_exchange_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.batteryexchange')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
