# Generated by Django 4.0.2 on 2022-02-12 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_remove_afterservice_owner_afterservice_vehicle'),
        ('member', '0003_alter_member_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberownedvehicles',
            name='recent_exchange_history',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.batteryexchange'),
        ),
    ]
