# Generated by Django 4.0.2 on 2022-03-05 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_card_alter_user_groups_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
