# Generated by Django 4.0.1 on 2022-02-08 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_remove_member_phone_number_member_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='number',
            new_name='member_info_number',
        ),
    ]
