# Generated by Django 4.0.2 on 2022-02-16 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productimage_product_and_more'),
        ('member', '0004_alter_memberownedvehicles_recent_exchange_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberownedvehicles',
            name='order',
        ),
        migrations.RemoveField(
            model_name='memberownedvehicles',
            name='recent_exchange_history',
        ),
        migrations.AlterField(
            model_name='memberownedvehicles',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.vehicle'),
        ),
    ]
