# Generated by Django 4.0.2 on 2022-03-05 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_paymentmethod_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_company',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='security_code',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='validate_date',
            field=models.DateField(null=True),
        ),
    ]
