# Generated by Django 4.0.2 on 2022-03-10 06:52

from django.db import migrations, models
import member.constant


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_alter_paymentmethod_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_company',
            field=models.PositiveSmallIntegerField(default=member.constant.CardCompany['ETC'], null=True),
        ),
    ]
