# Generated by Django 4.0.2 on 2022-03-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_alter_card_card_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_company',
            field=models.CharField(choices=[('BC', 'Bc'), ('KB', 'Kb'), ('SAMSUNG', 'Samsung'), ('SHINHAN', 'Shinhan'), ('UURI', 'Uuri'), ('HANA', 'Hana'), ('LOTTE', 'Lotte'), ('HYUNDAI', 'Hyundai'), ('NH', 'Nh'), ('ETC', 'Etc')], default='ETC', max_length=10),
        ),
    ]
