# Generated by Django 4.0.2 on 2022-03-11 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_alter_card_card_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_company',
            field=models.CharField(choices=[('bc', 'Bc'), ('kb', 'Kb'), ('samsung', 'Samsung'), ('shinhan', 'Shinhan'), ('uuri', 'Uuri'), ('hana', 'Hana'), ('lotte', 'Lotte'), ('hyundai', 'Hyundai'), ('nh', 'Nh'), ('etc', 'Etc')], default='etc', max_length=10),
        ),
    ]
