# Generated by Django 4.0.2 on 2022-03-11 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='member_info_number',
        ),
    ]
