# Generated by Django 4.0.2 on 2022-03-11 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0012_remove_user_member_info_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_business',
        ),
    ]
