# Generated by Django 4.0.2 on 2022-02-10 07:50

from django.db import migrations, models
import django.db.models.deletion
import history.constant


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('placement', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_created', models.DateTimeField(auto_now_add=True)),
                ('is_updated', models.DateTimeField(auto_now=True)),
                ('reject_reason', models.CharField(blank=True, max_length=200)),
                ('reject_method', models.CharField(blank=True, max_length=200)),
                ('status', models.PositiveSmallIntegerField(default=history.constant.RefundStatus['WAITING'])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntegratedFeePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_created', models.DateTimeField(auto_now_add=True)),
                ('is_updated', models.DateTimeField(auto_now=True)),
                ('cumulative_usage', models.IntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BatteryExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_created', models.DateTimeField(auto_now_add=True)),
                ('is_updated', models.DateTimeField(auto_now=True)),
                ('used_battery', models.FloatField(default=0.0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement.placement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AfterService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_created', models.DateTimeField(auto_now_add=True)),
                ('is_updated', models.DateTimeField(auto_now=True)),
                ('registration_number', models.CharField(max_length=16, unique=True)),
                ('license_code', models.CharField(max_length=200, null=True)),
                ('status', models.PositiveSmallIntegerField(default=history.constant.AfterServiceStatus['APPLY_WAITING'])),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement.placement')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
