# Generated by Django 4.0.2 on 2022-02-12 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='afterservice',
            name='license_code',
        ),
    ]
