# Generated by Django 4.0.2 on 2022-02-23 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('history', '0001_initial'),
        ('member', '0001_initial'),
        ('order', '0001_initial'),
        ('placement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
        migrations.AddField(
            model_name='batteryexchange',
            name='fee_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.integratedfeeplan'),
        ),
        migrations.AddField(
            model_name='batteryexchange',
            name='member_vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='member.memberownedvehicles'),
        ),
        migrations.AddField(
            model_name='batteryexchange',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
        migrations.AddField(
            model_name='batteryexchange',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement.placement'),
        ),
        migrations.AddField(
            model_name='afterservice',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement.placement'),
        ),
        migrations.AddField(
            model_name='afterservice',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='member.memberownedvehicles'),
        ),
    ]
