# Generated by Django 4.0.4 on 2022-05-11 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('placement', '0001_initial'),
        ('member', '0001_initial'),
        ('history', '0001_initial'),
        ('order', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
        migrations.AddField(
            model_name='cart',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='batteryexchange',
            name='fee_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.integratedfeeplan'),
        ),
        migrations.AddField(
            model_name='batteryexchange',
            name='member_vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='member.memberownedvehicles'),
        ),
        migrations.AddField(
            model_name='batteryexchange',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
        migrations.AddField(
            model_name='batteryexchange',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement.placement'),
        ),
        migrations.AddField(
            model_name='afterservice',
            name='owned_vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='member.memberownedvehicles'),
        ),
        migrations.AddField(
            model_name='afterservice',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement.placement'),
        ),
        migrations.AddField(
            model_name='afterservice',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
