# Generated by Django 4.0.2 on 2022-02-12 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('history', '0002_remove_afterservice_license_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='afterservice',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='member.member'),
        ),
    ]
