# Generated by Django 4.0.3 on 2022-04-15 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('history', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='afterservice',
            old_name='vehicle',
            new_name='owned_vehicle',
        ),
        migrations.AddField(
            model_name='afterservice',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
