# Generated by Django 4.0.2 on 2022-02-12 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_alter_member_id_and_more'),
        ('history', '0003_afterservice_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='afterservice',
            name='owner',
        ),
        migrations.AddField(
            model_name='afterservice',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='member.memberownedvehicles'),
        ),
    ]
