# Generated by Django 4.0.2 on 2022-02-14 13:34

from django.db import migrations, models
import history.constant


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_remove_afterservice_owner_afterservice_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='reject_method',
        ),
        migrations.AddField(
            model_name='refund',
            name='method',
            field=models.PositiveSmallIntegerField(default=history.constant.RefundMethod['RECALL_REQUEST']),
        ),
    ]
