# Generated by Django 4.0.2 on 2022-02-16 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_integratedfeeplan'),
        ('member', '0005_remove_memberownedvehicles_order_and_more'),
        ('history', '0006_warranty_afterservice_category_afterservice_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batteryexchange',
            name='fee_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.integratedfeeplan'),
        ),
        migrations.AddField(
            model_name='batteryexchange',
            name='member_vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='member.memberownedvehicles'),
        ),
        migrations.DeleteModel(
            name='IntegratedFeePlan',
        ),
    ]
