# Generated by Django 4.0.4 on 2022-04-28 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import order.constant


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraSubside',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_created', models.DateTimeField(auto_now_add=True)),
                ('is_updated', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제일')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.IntegerField(default=0)),
                ('description_1', models.TextField(blank=True, help_text='보조금 신청 시 필요 서류 및 안내')),
                ('description_2', models.TextField(blank=True, help_text='보조금 신청 시 주의 사항')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntegratedFeePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제일')),
                ('zentrophy_fee', models.IntegerField(default=0)),
                ('battery_fee', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_created', models.DateTimeField(auto_now_add=True)),
                ('is_updated', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제일')),
                ('buy_list', models.JSONField(default=dict, null=True)),
                ('subside', models.BooleanField(default=False)),
                ('is_visited', models.BooleanField(default=False)),
                ('total', models.IntegerField(default=0)),
                ('state', models.PositiveSmallIntegerField(default=order.constant.OrderState['ACCEPT_ORDER'])),
                ('extra_subside', models.ManyToManyField(to='order.extrasubside')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subside',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제일')),
                ('amount', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제일')),
                ('amount', models.IntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('product_options', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productoptions')),
                ('vehicle_color', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.vehiclecolor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NecessaryDocumentFile',
            fields=[
                ('is_created', models.DateTimeField(auto_now_add=True)),
                ('is_updated', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='order/%Y/%M')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='extrasubside',
            name='subside',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.subside'),
        ),
    ]
