# Generated by Django 4.0.1 on 2022-02-03 07:19

from django.db import migrations, models
import order.constant


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('is_created', models.DateTimeField(auto_now_add=True)),
                ('is_updated', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(blank=True, max_length=100)),
                ('amount', models.IntegerField()),
                ('state', models.PositiveSmallIntegerField(default=order.constant.OrderState['ACCEPT_ORDER'])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
