# Generated by Django 4.0.2 on 2022-02-23 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_vehicle',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
