# Generated by Django 4.0.1 on 2022-02-06 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_rename_thumb-product121278856358952_productimage_origin_image_and_more'),
        ('member', '0004_remove_member_phone_number_member_number_and_more'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraSubside',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('amount', models.IntegerField(default=0)),
                ('description_1', models.TextField(blank=True)),
                ('description_2', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subside',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_name',
        ),
        migrations.AddField(
            model_name='order',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_owner', to='member.member'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(null=True, related_name='order_product', to='product.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='vehicle',
            field=models.ManyToManyField(null=True, related_name='order_vehicle', to='product.Vehicle'),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='NecessaryDocumentFile',
            fields=[
                ('is_created', models.DateTimeField(auto_now_add=True)),
                ('is_updated', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='document/%Y/%M')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='extra_subside',
            field=models.ManyToManyField(null=True, related_name='order_extra_subside', to='order.ExtraSubside'),
        ),
    ]
