# Generated by Django 4.0.2 on 2022-02-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_is_vehicle_alter_order_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegratedFeePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zentrophy_fee', models.IntegerField(default=0)),
                ('battery_fee', models.IntegerField(default=0)),
            ],
        ),
    ]
