# Generated by Django 4.0.1 on 2022-02-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_rename_thumb-product121278856358952_productimage_origin_image_and_more'),
        ('order', '0002_extrasubside_subside_remove_order_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='extra_subside',
            field=models.ManyToManyField(related_name='order_extra_subside', to='order.ExtraSubside'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(related_name='order_product', to='product.Product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='vehicle',
            field=models.ManyToManyField(related_name='order_vehicle', to='product.Vehicle'),
        ),
    ]
