# Generated by Django 4.0.1 on 2022-02-06 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_extra_subside_alter_order_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subside',
        ),
    ]
