# Generated by Django 4.0.1 on 2022-02-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_productimage_origin_image_and_more'),
        ('order', '0004_delete_subside'),
    ]

    operations = [
        migrations.AlterField(
            model_name='necessarydocumentfile',
            name='file',
            field=models.FileField(upload_to='order/%Y/%M'),
        ),
        migrations.AlterField(
            model_name='order',
            name='extra_subside',
            field=models.ManyToManyField(to='order.ExtraSubside'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(to='product.Product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='vehicle',
            field=models.ManyToManyField(to='product.Vehicle'),
        ),
    ]
