# Generated by Django 4.0.1 on 2022-02-06 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_remove_member_phone_number_member_number_and_more'),
        ('order', '0005_alter_necessarydocumentfile_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.member'),
        ),
    ]
