# Generated by Django 4.0.1 on 2022-02-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_info',
            field=models.JSONField(null=True),
        ),
    ]
