# Generated by Django 4.0.1 on 2022-02-07 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_order_product_remove_order_vehicle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
    ]
