# Generated by Django 4.0.1 on 2022-02-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_necessarydocumentfile_order_alter_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrasubside',
            name='description_1',
            field=models.TextField(blank=True, help_text='보조금 신청 시 필요 서류 및 안내'),
        ),
        migrations.AlterField(
            model_name='extrasubside',
            name='description_2',
            field=models.TextField(blank=True, help_text='보조금 신청 시 주의 사항'),
        ),
    ]
