# Generated by Django 4.0.1 on 2022-02-08 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_extrasubside_description_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='subside',
            field=models.IntegerField(default=0),
        ),
    ]
