# Generated by Django 4.0.1 on 2022-02-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_order_subside'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='subside',
        ),
        migrations.AddField(
            model_name='order',
            name='is_able_subside',
            field=models.BooleanField(default=False),
        ),
    ]
